name:                cllthask
version:             0.1.0.0
github:              "Hexirp/cllthask"
license:             BSD3
author:              "Hexirp"
maintainer:          "Hexirp@users.noreply.github.com"
copyright:           "2018 Hexirp"

extra-source-files:
- README.md

# synopsis:            Short description of your package
# category:            Other

description:         Please see the README on GitHub at <https://github.com/Hexirp/cllthask#readme>

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src

executables:
  cllthask-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cllthask

tests:
  cllthask-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cllthask
